### ISSUE TITLE
Invalid Group expression usage

### ISSUE THREAD

**Issue by dcomartin** [umutozel/DynamicQueryable#4]
## DynamicQueryable version
2.0.25

## Steps to reproduce
https://gist.github.com/dcomartin/3e6fff415f6886c1b3c3b50b377fa0fc

## Expected  behavior
Should behave and return the same results as the linq statement.

## Actual behavior
Throws a System.Exception: Invalid Group expression usage.  This is from the Jokenizer which this package depends on.

**Comment by umutozel** [comment]
Fixed with 1.1.1 version.

**Comment by gbreen12** [comment]
I think I'm still seeing this problem on 2.0.25. Might be something different but it's the same error. This is what I've got:
```
var where = "(FirstName.ToLower().Contains(@0) || FirstName.ToLower().Contains(@1)) && (LastName.ToLower().Contains(@0) || LastName.ToLower().Contains(@1))"
var searchTerms = new List<string> { "ron", "edwards" };
query = query.Where(where, searchTerms);
```
